# Dev notebook

I use this notebook to develop my implementation of a simple and minimal neural network framework.

Inspiration for this network is drawn from the book [Neural Networks from Scratch (NNFS)](https://nnfs.io/) & [Pytorch's implementation](https://pytorch.org/)

Notes:
- The work on experimenting with backpropagation has been moved to another notebook to keep this one minimal
- I have chosen to use a similar naming convention to that used by pytorch (why reinvent the wheel), this has the benefit of ensuring that when we compare implementations the architecture of the networks is the same. 

In [1]:
# Import for dev and testing
import nnfs 
import numpy as np

import matplotlib.pyplot as plt

from abc import ABC, abstractmethod
from nnfs.datasets import spiral_data
from typing import List

nnfs.init()

## Defining Base Module

This is a module that contains all the base attributes and function needed by every class in the framework

In [2]:
class Module(ABC):
    """Base class for all classes in frame work to ensure the same attributes and common function names."""

    def __init__(self) -> None:
        # Attributes to hold input and outputs
        self.input = None
        self.output = None
    
    @abstractmethod
    def forward(self):
        pass

    @abstractmethod
    def backward(self):
        pass

##  Defining layers 

In this section We define and test the layers

Notes:
- since we intend to use ReLU as one of our activation functions we will use the He weight initialization method as described in https://arxiv.org/abs/1502.01852

### Linear Layer

In [3]:
class LinearLayer(Module):
    """Linear transformation layer of the type o = ixW + b,
    
    where I is the incoming vector, W is the layers weight matrix, b is bias vector and o is the dot product of the 
    i and W plus the bias
    
    Args:
        in_features (int): the size of the input features 
        out_features (int): the size of the output features
        
    Attributes:
        weights (np_array) numpy array of in_features x n_neurons
        biases  (np_array) numpy array of 1 x n_neurons
        inputs  (np_array) numpy array of latest batch of inputs
        inputs  (np_array) numpy array of latest batch of outputs
        d_w     (np_array) The current gradients with respect to the weights 
        d_x     (np_array) The current gradients with respect to the inputs
        d_b     (np_array) The current gradients with respect to the biases
    """

    def __init__(self, in_features, out_features, 
                 lambda_l1_weight=0, lambda_l1_bias=0, 
                 lambda_l2_weight=0, lambda_l2_bias=0) -> None:
        super().__init__()
        # initializing weights and biases 
        #self.weights = np.random.normal(0.0, np.sqrt(2/in_features), (in_features, out_features))
        # Using a simpler initialization  for testing 
        self.weights = 0.01 * np.random.randn(in_features, out_features)
        self.bias = np.zeros((1, out_features))
        # initializing regularization lambdas
        if (lambda_l1_bias > 0) | (lambda_l1_weight > 0):
            self.lambda_l1_weight = lambda_l1_weight
            self.lambda_l1_bias = lambda_l1_bias
        else:
            self.lambda_l1_weight = None
            self.lambda_l1_bias = None
        if (lambda_l2_bias > 0) | (lambda_l2_weight > 0):  
            self.lambda_l2_weight = lambda_l2_weight
            self.lambda_l2_bias = lambda_l2_bias
        else: 
            self.lambda_l2_weight = None
            self.lambda_l2_bias = None

    def forward(self, inputs):
        # Saving inputs for backward step
        self.input = inputs
        self.output = np.dot(inputs, self.weights) + self.bias
        return self.output

    def l1_backward_w(self):
        if self.lambda_l1_weight:
            d_l1 = np.ones_like(self.weights) 
            d_l1[self.weights < 0] = -1
            return d_l1 * self.lambda_l1_weight
        else:
            return 0

    def l1_backward_b(self):
        if self.lambda_l1_bias:
            d_l1 = np.ones_like(self.bias) 
            d_l1[self.bias < 0] = -1
            return d_l1 * self.lambda_l1_bias
        else:
            return 0  

    def l2_backward_w(self):
        if self.lambda_l2_weight:
            return 2 * self.lambda_l2_weight  * self.weights
        else:
            return 0
        
    def l2_backward_b(self):
        if self.lambda_l2_bias:
            return 2 * self.lambda_l2_bias  * self.bias
        else:
            return 0

    def backward(self, d_vals):
        """Backpropagation  of the linear function

        Args:
            d_vals (np_array) array of derivatives from the previous layer/function.
        """
        self.d_w = np.dot(self.input.T, d_vals) + self.l1_backward_w() + self.l2_backward_w()
        self.d_b = np.sum(d_vals, axis=0, keepdims=True) + self.l1_backward_b() + self.l2_backward_b()

        self.grad = np.dot(d_vals, self.weights.T)

    def regularization_loss(self):
        loss = 0
        # L1 weight 
        if self.lambda_l1_weight:
            loss += self.lambda_l1_weight * np.sum(np.abs(self.weights))
        # L1 bias
        if self.lambda_l1_bias:
            loss += self.lambda_l1_bias * np.sum(np.abs(self.bias))
        # L2 weight
        if self.lambda_l2_weight:
            loss += self.lambda_l2_weight * np.sum(self.weights * self.weights)
        # L2 bias
        if self.lambda_l2_bias:
            loss += self.lambda_l2_bias * np.sum(self.bias * self.bias)

        return loss


#### Testing Linear Layer

In [4]:
# The sample data is a list of coordinate, ie two points 
# The layer therefore will take 2 inputs 
# We have given it 3 out features (3 neurons) so we expect to see an output with the shape (n_samples*n_neurons, n_neurons)
# In out case that should be (300, 3) 
X, _ = spiral_data(samples=100, classes=3)
linear1 = LinearLayer(2, 3)
output = linear1.forward(X)
print(output[:10, :])

assert output.shape == (300,3)


[[ 0.0000000e+00  0.0000000e+00  0.0000000e+00]
 [-1.0475188e-04  1.1395361e-04 -4.7983500e-05]
 [-2.7414842e-04  3.1729150e-04 -8.6921798e-05]
 [-4.2188365e-04  5.2666257e-04 -5.5912682e-05]
 [-5.7707680e-04  7.1401405e-04 -8.9430439e-05]
 [-3.5430698e-04  3.5025488e-04 -2.3363481e-04]
 [-8.9267001e-04  1.0767876e-03 -1.9453237e-04]
 [-9.3350781e-04  1.0723802e-03 -3.1227397e-04]
 [-1.1243758e-03  1.3112801e-03 -3.3629674e-04]
 [-1.3386955e-03  1.6200906e-03 -2.8101794e-04]]


## Defining Dropout

The drop out layer will take one hyperparameter, rate,  which will represent the percentage of neurons that will be deactivated with each forward pass. 

To achieve this will will make a mask the size of the output of the previous layer (number of neurons) and apply a binomial distribution. The distribution will be used to generate an array of zero or ones that will be multiplied against the output of the previous layer. This will deactivate or zero out those outputs that correspond to the zeros generated to the binomial dist.


In [5]:
class Dropout(Module):
    """Where rate is the # of neurons to keep active (same as in pytorch vs Keras/TensorFlow style where it would be to deactivate)"""

    def __init__(self, rate:float) -> None:
        super().__init__()
        self.rate = rate
        self.mask = None
        self.training_mode = True

    def forward(self, input:np.ndarray) -> np.ndarray:
        if not self.training_mode:
            self.output = input
            return self.output

        self.input = input
        self.mask = np.random.binomial(1, self.rate, size=input.shape)/ self.rate
        self.output = input * self.mask  # note we scale the output by the rate to account for the omission of dropout during model evaluation 
        return self.output
    
    def backward(self, grads):
        self.grad = grads * self.mask
    

### Testing Dropout

In [6]:
# using the output of the previous test
input = output[:10, :]
rate = 0.8 # deactivate 10% of the neurons

dropout = Dropout(rate)
dropout.forward(input)

array([[ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [-1.30939852e-04,  1.42442013e-04, -5.99793748e-05],
       [-3.42685526e-04,  0.00000000e+00, -1.08652248e-04],
       [-0.00000000e+00,  0.00000000e+00, -6.98908525e-05],
       [-7.21346005e-04,  8.92517564e-04, -1.11788049e-04],
       [-4.42883720e-04,  4.37818599e-04, -2.92043514e-04],
       [-1.11583751e-03,  1.34598449e-03, -2.43165468e-04],
       [-1.16688476e-03,  1.34047528e-03, -3.90342466e-04],
       [-1.40546981e-03,  1.63910008e-03, -0.00000000e+00],
       [-0.00000000e+00,  2.02511321e-03, -3.51272429e-04]])

## Defining Activation Functions

### ReLu

$$y = \begin{cases}
   x &x> 0 \\
   0 & otherwise
\end{cases} $$

In [7]:
class ReLU(Module):
    """Applies Rectified linear Unit function to vector."""
    def __init__(self) -> None:
        # initializing attributes needed for backwards 
        super().__init__()
        self.grad = None
    
    def forward(self, x):
        # storing inputs needed for backwards 
        self.inputs = x
        self.output = np.maximum(x, 0)
        return self.output
    
    def backward(self, d_vals):
        self.grad = d_vals.copy()
        self.grad[self.inputs <= 0] = 0

#### Testing ReLU

In [8]:
i = [-2, 3, 4, 0, 0.1, -44]
test_relu = ReLU()

# Checking values are as expected 
assert np.all(np.array([0., 3, 4, 0, 0.1, 0.]) == test_relu.forward(i))

test_relu.output

array([0. , 3. , 4. , 0. , 0.1, 0. ])

### Softmax

$$\text{softmax}(x)_i = \frac{exp(x_i)}{\sum_{j}^{ }exp(x_j))}$$

The soft max represents the confidence score for each output class and adds up to 1.

In [9]:
class Softmax(Module):
    """Applies Softmax function to input matrix."""

    def __init__(self) -> None:
        super().__init__()
        self.confidence_scores = None

    def forward(self, x):
        # exponenets of each value
        exp_vals = np.exp(x - np.max(x, axis=1, keepdims=True))
        exp_sum = np.sum(exp_vals, axis=1, keepdims=True)
        # Normalization to get the proabilities 
        self.output = exp_vals/exp_sum
        return self.output

    def _backward(self, d_vals):
        # Initialize array for gradients wrt to inputs
        self.grad = np.zeros_like(d_vals)
        
        _iter = enumerate(zip(self.output, d_vals))
        for i, conf_score, d_val in _iter:
            # Flatten confidence scores
            cs = conf_score.reshape(-1, 1)
            # Find the Jacobian matrix of the output 
            j_matrix = np.diagflat(cs) - np.dot(cs, cs.T)
            # get the gradient 
            self.grad[i] = np.dot(j_matrix, d_val)
    
    def backward(self, y_pred, y_true):
        """Does a the combined backward pass for CCE & Softmax as a single, faster step."""
        # Number of examples in the batch
        n = len(y_pred)

        # Getting descrete vals from one hot encoding 
        y_true = np.argmax(y_true, axis=1)
        
        self.grad = y_pred.copy()
        self.grad[range(n), y_true] -= 1
        self.grad = self.grad / n
        return self.grad


#### Testing Softmax

In [10]:
softmax = Softmax()
softmax.forward([[1,2,44]])

array([[2.11513104e-19, 5.74952226e-19, 1.00000000e+00]])

## Defining Loss - Categorical Cross-Entropy

$$ L_i = -\sum_j y_{i,j}\log(\hat{y}_{i,j}) $$

With taking one hot encoding into account we can simplify this down to:

$$ L_i = -y_{i,k}\log(\hat{y}_{i,k}) $$

where K is the index of the correct class

In [11]:
class CategoricalCrossEntropyLoss:
    """Calculates the CCE loss for a given set of predictions.
    This method expect a softmax output and one-hot encoded label mask
    
    y_pred (np_array): matrix of confidence scores of the prediction
    y_true (np_array): matrix of one-hot encoded true lables of the classes
    """
    def forward(y_pred, y_true):
        # Clipping and applying one hot encoded labels as mask 
        # to zero out scores corresponding to incorrect classes
        # We clip to make sure that none of the reaming classes are 0 or 
        # exactly 1 
        clipped = np.clip(y_pred, 1e-7, 1 - 1e-7)
        corrected = np.sum(clipped*y_true, axis=1)
        # Taking the -ve log of the remaining confidence scores 
        negative_log = -np.log(corrected)
        return np.mean(negative_log)

    def backward(y_pred, y_true):
        """Backpropagation  of the CCE Loss

        Args:
            y_pred (np_array) array of predictions.
            y_true (np_array) array of correct labels.
        """
        return (-y_true/y_pred)/len(y_pred)

#### Testing CCE Loss

In [12]:
y_pred = np.array([[0.7, 0.1, 0.2], [0.1,0.5,0.4],[0.02,0.9,0.08]])
y_true = np.array([[1,0,0], [0,1,0], [0,1,0]])

loss_function = CategoricalCrossEntropyLoss
loss_function.forward(y_pred, y_true)

0.38506088005216804

## Defining Optimizers

### Stochastic Gradient Decent 

$$ \text{Update} = -\text{Learning Rate} \cdot \text{Gradient}$$

In [13]:
class SDG:
    """Stochastic Gradient Decent class used to update layer paramers
    The update is the -ve learning rate multiplied by the gradient calculated in the backward step.

    Attr:
        lr (float) Learning rate to scale the gradients by for the update
    """
    IMPLEMENTED = [LinearLayer]

    def __init__(self, learning_rate=1, decay=0., momentum=0.) -> None:
        self.lr = learning_rate
        self.clr = learning_rate # current learning rate
        self.decay = decay
        self.momentum = momentum
        self.iterations = 0

    def init_momentum(self, layers):
        for layer in layers:
            if not hasattr(layer, 'momentum_w'):
                layer.momentum_w = np.zeros_like(layer.weights)
                layer.momentum_b = np.zeros_like(layer.bias)

    def pre_update_step(self):
        decay_rate = 1/(1 + self.decay * self.iterations)
        self.clr = self.lr * decay_rate

    def get_updates(self, layer):
        return (
            -self.clr*layer.d_w,
            -self.clr*layer.d_b
        )

    def get_momentum_updates(self, layer):
        wu = (self.momentum * layer.momentum_w) - (self.clr * layer.d_w) 
        bu = (self.momentum * layer.momentum_b) - (self.clr * layer.d_b) 
        layer.momentum_w = wu
        layer.momentum_b = bu
        return (wu, bu)

    def update(self, layers):
        """Update a layers parameters.
        """
        # Test to make sure all layers supported
        if any(l for l in layers if type(l) not in self.IMPLEMENTED):
            unsupported = next(l for l in layers if type(l) not in self.IMPLEMENTED)
            raise NotImplementedError(f'SDG does not support {unsupported.__class__}')

        # pre update step
        if self.decay:
            self.pre_update_step()

        # On the first iteration using momentum initialize the layer momentums
        if self.iterations == 0 and self.momentum:
            self.init_momentum(layers)

        # Update step
        for layer in layers:

            if self.momentum:
                weight_u, bias_u = self.get_momentum_updates(layer)
            else:
                weight_u, bias_u = self.get_updates(layer)
            
            layer.weights += weight_u
            layer.bias += bias_u

        # post update
        self.iterations += 1 

### Adam

Short for Adaptive Momentum.

An extension to the Root mean square propagation (RSMprop) technique that adds in a bias correction mechanism used to correct the momentum and momentum caches.

To find the update with Adam we need to take the following steps:

1. Find momentum for the current step
2. Get corrected the momentum 
3. Update the cache with the square of the gradient 
4. Get the corrected cache 
5. Update weights 


In the first step we calculate the layer weight and bias momentums by:

$$ \text{Layer Momentum} = (\beta_1 \cdot \text{Layer Momentum}) + ((1 - \beta_1) \cdot gradient)$$ 

where $\beta_1$ is a hyper-parameter that allows us to apply fractions of the momentum and gradient at each step. 

To correct this we then divide the momentum by bias correction mechanism: 

$$ \text{Corrected Momentum} = \frac{\text{Layer Momentum}}{1 - \beta_1^{n+1}} $$

where $n$ is the number of the iteration/epoch and we add 1 to it to account for initializing it from 0

Next we update the cache for the weights and biases:

$$ \text{Cache} = (\beta_2 \cdot \text{Cache}) + ((1 - \beta_2) * \text{gradients}^2)$$

We once again correct, this time the cache, with Adam's bias correction mechanism:

$$ \text{Corrected Cache} = \frac{\text{Cache}}{{1 - \beta_2^{n+1}}}$$

Finally to update the weights we do the following:

$$ \text{Update} = \frac{\text{Current Learning Rate} \cdot \text{Corrected Momentum}}{\sqrt{\text{Corrected Cache}} + \epsilon} $$ 


In [14]:
class Adam:
    """Adam Optimizer"""

    IMPLEMENTED = [LinearLayer]

    def __init__(self, learning_rate=0.001, decay=0., epsilon=1e-7, beta_1=0.9, beta_2=0.999) -> None:
        self.lr = learning_rate
        self.clr = learning_rate # current learning rate
        self.decay = decay
        self.epsilon = epsilon
        self.beta_1 = beta_1
        self.beta_2 = beta_2
        self.iterations = 0

    def pre_update_step(self):
        decay_rate = 1/(1 + self.decay * self.iterations)
        self.clr = self.lr * decay_rate

    def init_momentum(self, layers:List[LinearLayer]):
        for layer in layers:
            # Init momentum for weights
            layer.momentums_w = np.zeros_like(layer.weights)
            layer.cache_w = np.zeros_like(layer.weights)

            # Init momentums for biases
            layer.momentums_b = np.zeros_like(layer.bias)
            layer.cache_b = np.zeros_like(layer.bias)
            

    def update(self, layers:List[LinearLayer]):
        # pre update step
        if self.decay:
           self.pre_update_step()
        
        if self.iterations == 0:
            self.init_momentum(layers)

        # Update step
        for layer in layers:     
            ## Updating momentum 
            layer.momentums_w = self.beta_1 * layer.momentums_w + (1 - self.beta_1) * layer.d_w
            layer.momentums_b = self.beta_1 * layer.momentums_b + (1 - self.beta_1) * layer.d_b

            ## Correcting momentum 
            correction_bias_momentums = 1 - self.beta_1**(self.iterations +1)

            corrected_weights = layer.momentums_w / correction_bias_momentums
            corrected_bias    = layer.momentums_b / correction_bias_momentums

            ## Updating cache
            layer.cache_w = self.beta_2 * layer.cache_w + (1 - self.beta_2) * layer.d_w**2
            layer.cache_b = self.beta_2 * layer.cache_b + (1 - self.beta_2) * layer.d_b**2

            ## Correcting cache
            correction_bias_cache = 1 - self.beta_2**(self.iterations +1)

            corrected_cache_w = layer.cache_w / correction_bias_cache
            corrected_cache_b = layer.cache_b / correction_bias_cache

            ## Updating weights 
            layer.weights += -self.clr * corrected_weights / (np.sqrt(corrected_cache_w) + self.epsilon)

            ## Updating bias
            layer.bias    += -self.clr * corrected_bias / (np.sqrt(corrected_cache_b) + self.epsilon)
        
        # Post update step
        self.iterations += 1



## Defining Utility functions

### One-hot encoding function 

In [15]:
def one_hot_encode_index(y, n):
    return np.eye(n)[y]

#### Testing one hot masker

In [16]:
n=3
y_test = np.array([0,1,2, 1, 2])

one_hot_encode_index(y_test, n)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)

### Define Accuracy 

In [17]:
def accuracy(y_pred, y_true):
    """Calculates the accuracy of a batch of predictions"""
    return np.mean(np.argmax(y_pred, axis=1) == np.argmax(y_true, axis=1))

## Defining Regularization 

Regularization methods are used to reduce generalization errors, With L1 and L2 regularization we calculate a penalty that we add to the loss if weight and biases are large. We want to see many neurons contribute to the evaluation rather than a few having a large impact.

L1 weight regularization: 

$$ L_{1w} = \lambda\sum_m|w_m| $$

L1 bias regularization: 

$$ L_{1b} = \lambda\sum_n|b_n| $$

L2 weight regularization: 

$$ L_{2w} = \lambda\sum w^2_m $$

L2 bias regularization: 

$$ L_{2b} = \lambda\sum_n b^2_n $$

Overall loss:

$$ \text{Loss} = \text{DataLoss} + L_{1w} + L_{1b} + L_{2w} + L_{2b} $$


To implement these changes we will need to modify the Linear Layer class.

(note: for backpropagation see backpropagation notebook)



## Integration Testing 

### Test with SDG

In [18]:
nnfs.init()
X, y = spiral_data(samples=100, classes=3)
y = one_hot_encode_index(y, 3)

# Initializing Network Components 
relu = ReLU()
softmax = Softmax()
cce_loss = CategoricalCrossEntropyLoss
optimizer = SDG(decay=1e-3, momentum=0.9)
linear1 = LinearLayer(2, 64, lambda_l2_weight=5e-4, lambda_l2_bias=5e-4)
linear2 = LinearLayer(64, 3)

update_layers = [linear1, linear2]

n_epochs = 10000

for epoch in range(n_epochs + 1):
    # Forward Pass
    linear1.forward(X) 
    relu.forward(linear1.output)
    linear2.forward(relu.output)
    y_pred = softmax.forward(linear2.output)

    # Calculating loss and regularized loss  
    loss = cce_loss.forward(y_pred, y)
    # Regularised loss
    rl = sum([l.regularization_loss() for l in update_layers if hasattr(l, 'regularization_loss')])
    regularized_loss = loss + rl

    #Calculating accuracy 
    acc = accuracy(y_pred, y) 

    # Printing results
    if not epoch % 100:
        print(f"Epoch:{epoch}, Loss:{loss:.3f}, Reg loss: {regularized_loss:.3f}, ({rl:.3f}), accuracy:{acc:.3f}")

    # Backward pass
    softmax.backward(y_pred, y)
    linear2.backward(softmax.grad)
    relu.backward(linear2.grad)
    linear1.backward(relu.grad)

    # Optimization Step
    optimizer.update(update_layers)
    

Epoch:0, Loss:1.099, Reg loss: 1.099, (0.000), accuracy:0.360
Epoch:100, Loss:1.052, Reg loss: 1.055, (0.003), accuracy:0.447
Epoch:200, Loss:0.986, Reg loss: 1.009, (0.024), accuracy:0.500
Epoch:300, Loss:0.870, Reg loss: 0.910, (0.040), accuracy:0.570
Epoch:400, Loss:0.881, Reg loss: 0.964, (0.083), accuracy:0.597
Epoch:500, Loss:0.718, Reg loss: 0.798, (0.080), accuracy:0.657
Epoch:600, Loss:0.872, Reg loss: 0.957, (0.085), accuracy:0.567
Epoch:700, Loss:0.620, Reg loss: 0.711, (0.090), accuracy:0.700
Epoch:800, Loss:0.579, Reg loss: 0.673, (0.095), accuracy:0.743
Epoch:900, Loss:0.590, Reg loss: 0.684, (0.094), accuracy:0.740
Epoch:1000, Loss:0.646, Reg loss: 0.769, (0.123), accuracy:0.683
Epoch:1100, Loss:0.536, Reg loss: 0.639, (0.103), accuracy:0.773
Epoch:1200, Loss:0.556, Reg loss: 0.656, (0.100), accuracy:0.747
Epoch:1300, Loss:0.537, Reg loss: 0.638, (0.102), accuracy:0.747
Epoch:1400, Loss:0.519, Reg loss: 0.619, (0.100), accuracy:0.790
Epoch:1500, Loss:0.502, Reg loss: 0.6

In [19]:
# Validating the model 
X_test, y_test = spiral_data(samples=100, classes=3)
y_test = one_hot_encode_index(y_test, 3)

linear1.forward(X_test) 
relu.forward(linear1.output)
linear2.forward(relu.output)
y_pred = softmax.forward(linear2.output)

# Calculating loss and accuracy 
loss = cce_loss.forward(y_pred, y_test)
acc = accuracy(y_pred, y_test) 

print(f'Vallidation: Accuracy: {acc:.3f}, loss: {loss:.3f}')

Vallidation: Accuracy: 0.767, loss: 0.515


### Test with Adam

In [20]:
X, y = spiral_data(samples=1000, classes=3)
y = one_hot_encode_index(y, 3)

# Initializing Network Components 
relu = ReLU()
softmax = Softmax()
cce_loss = CategoricalCrossEntropyLoss
optimizer = Adam(learning_rate=0.05, decay=5e-5)
dropout = Dropout(0.9)
linear1 = LinearLayer(2, 64, lambda_l2_weight=5e-4, lambda_l2_bias=5e-4)
linear2 = LinearLayer(64, 3)

update_layers = [linear1, linear2]

n_epochs = 10000

for epoch in range(n_epochs + 1):
    # Forward Pass
    linear1.forward(X) 
    relu.forward(linear1.output)
    dropout.forward(relu.output)
    linear2.forward(dropout.output)
    y_pred = softmax.forward(linear2.output)

    # Calculating loss and regularized loss  
    loss = cce_loss.forward(y_pred, y)
    # Regularised loss
    rl = sum([l.regularization_loss() for l in update_layers if hasattr(l, 'regularization_loss')])
    regularized_loss = loss + rl

    #Calculating accuracy 
    acc = accuracy(y_pred, y) 

    # Printing results
    if not epoch % 100:
        print(f"Epoch:{epoch}, Loss:{loss:.3f}, Reg loss: {regularized_loss:.3f}, ({rl:.3f}), accuracy:{acc:.3f}")

    # Backward pass
    softmax.backward(y_pred, y)
    linear2.backward(softmax.grad)
    dropout.backward(linear2.grad)
    relu.backward(dropout.grad)
    linear1.backward(relu.grad)

    # Optimization Step
    optimizer.update(update_layers)


Epoch:0, Loss:1.099, Reg loss: 1.099, (0.000), accuracy:0.373
Epoch:100, Loss:0.871, Reg loss: 0.899, (0.028), accuracy:0.592
Epoch:200, Loss:0.785, Reg loss: 0.822, (0.037), accuracy:0.636
Epoch:300, Loss:0.764, Reg loss: 0.803, (0.038), accuracy:0.652
Epoch:400, Loss:0.772, Reg loss: 0.809, (0.038), accuracy:0.653
Epoch:500, Loss:0.783, Reg loss: 0.819, (0.036), accuracy:0.647
Epoch:600, Loss:0.756, Reg loss: 0.790, (0.034), accuracy:0.661
Epoch:700, Loss:0.719, Reg loss: 0.752, (0.034), accuracy:0.679
Epoch:800, Loss:0.764, Reg loss: 0.796, (0.033), accuracy:0.645
Epoch:900, Loss:0.738, Reg loss: 0.770, (0.032), accuracy:0.659
Epoch:1000, Loss:0.730, Reg loss: 0.761, (0.031), accuracy:0.674
Epoch:1100, Loss:0.708, Reg loss: 0.737, (0.030), accuracy:0.678
Epoch:1200, Loss:0.721, Reg loss: 0.750, (0.029), accuracy:0.661
Epoch:1300, Loss:0.712, Reg loss: 0.740, (0.029), accuracy:0.674
Epoch:1400, Loss:0.710, Reg loss: 0.738, (0.028), accuracy:0.674
Epoch:1500, Loss:0.734, Reg loss: 0.7

In [21]:
# Validating the model 
X_test, y_test = spiral_data(samples=100, classes=3)
y_test = one_hot_encode_index(y_test, 3)

linear1.forward(X_test) 
relu.forward(linear1.output)
linear2.forward(relu.output)
y_pred = softmax.forward(linear2.output)

# Calculating loss and accuracy 
loss = cce_loss.forward(y_pred, y_test)
acc = accuracy(y_pred, y_test) 

print(f'Vallidation: Accuracy: {acc:.3f}, loss: {loss:.3f}')

Vallidation: Accuracy: 0.740, loss: 0.585


## Defining Model Object  

In [37]:
class Model:

    def __init__(self, optimizer, loss) -> None:
        self.layers = []
        self.trainable_layers = []
        self.loss = loss
        self.optim = optimizer
        self.current_loss = 0
        self.current_accuracy = 0
        self.training_mode = True

    def __repr__(self) -> str:
        layer_str = "".join([f"\t ({i}): {type(l).__name__} (Trainable: {l in self.trainable_layers})\n" 
                            for i, l in enumerate(self.layers)])

        return "Model Architecture: \n" + layer_str
    
    def add(self, layer):
        self.layers.append(layer)
        if hasattr(layer, 'weights'):
            self.trainable_layers.append(layer)

    def set_sequence(self, layers):
        self.layers = layers
        self.trainable_layers = [l for l in layers if hasattr(l, 'weights')]

    def get_loss(self, y_pred, y_true):
        # Calculating loss and regularized loss  
        loss = self.loss.forward(y_pred, y_true)
        # Regularised loss
        rl = sum([l.regularization_loss() for l in self.trainable_layers if hasattr(l, 'regularization_loss')])
        return loss + rl

    def forward(self, X):

        # First layer
        self.layers[0].forward(X)

        # Rest of layers 
        for i in range(1, len(self.layers)):
            self.layers[i].forward(self.layers[i-1].output)

    def backward(self, y_pred, y_true):
        # Last layer
        self.layers[-1].backward(y_pred, y_true)

        # Rest of the layers
        for i, l in reversed(list(enumerate(self.layers[:-1]))):
            l.backward(self.layers[i+1].grad)
        
    def logger(self, epoch):
        print(
            f"Epoch: {epoch}, accuracy{self.current_accuracy:.3f}, loss{self.current_loss:.3f}, learning rate {self.optim.clr:.3f} "
        )
    
    def validate(self, X_val, y_val):

        self.forward(X_val)

        loss = self.loss.forward(self.layers[-1].output, y_val)
        acc  = accuracy(self.layers[-1].output, y_val)

        print(
            f"Validation : Loss: {loss:.3f}, Accuracy: {acc:.3f}"
        )

    def mode_train(self):
        self.training_mode = True
        for l in self.layers:
            if type(l) == Dropout:
                l.training_mode = True
    
    def mode_eval(self):
        self.training_mode = False
        for l in self.layers:
            if type(l) == Dropout:
                l.training_mode = False
    
    def train(self, X, y, epochs=1, log=True, log_freq=100):
        
        for epoch in range(epochs + 1):

            # Forward Pass
            self.forward(X)

            # Loss 
            self.current_loss = self.get_loss(self.layers[-1].output, y)

            # accuracy 
            self.current_accuracy = accuracy(self.layers[-1].output, y) 
            
            # Backward Pass
            self.backward(self.layers[-1].output, y)

            # Optimization 
            self.optim.update(self.trainable_layers)

            # Logging 
            if log and not (epoch % log_freq):
                self.logger(epoch)

    

#### Testing Model Object

In [38]:
cce_loss = CategoricalCrossEntropyLoss
optimizer = Adam(learning_rate=0.05, decay=5e-5)

model = Model(optimizer, cce_loss)
model.set_sequence([
    LinearLayer(2, 512, lambda_l2_weight=5e-4, lambda_l2_bias=5e-4),
    ReLU(),
    Dropout(0.9),
    LinearLayer(512, 3)
])
model.add(Softmax())
model

Model Architecture: 
	 (0): LinearLayer (Trainable: True)
	 (1): ReLU (Trainable: False)
	 (2): Dropout (Trainable: False)
	 (3): LinearLayer (Trainable: True)
	 (4): Softmax (Trainable: False)

In [42]:
X, y = spiral_data(samples=1000, classes=3)
y = one_hot_encode_index(y, 3)
model.mode_train()
model.train(X, y, epochs=10000)

Epoch: 0, accuracy0.653, loss0.826, learning rate 0.050 
Epoch: 100, accuracy0.793, loss0.629, learning rate 0.050 
Epoch: 200, accuracy0.819, loss0.578, learning rate 0.049 
Epoch: 300, accuracy0.822, loss0.548, learning rate 0.049 
Epoch: 400, accuracy0.837, loss0.508, learning rate 0.049 
Epoch: 500, accuracy0.819, loss0.540, learning rate 0.049 
Epoch: 600, accuracy0.843, loss0.538, learning rate 0.048 
Epoch: 700, accuracy0.844, loss0.521, learning rate 0.048 
Epoch: 800, accuracy0.844, loss0.496, learning rate 0.048 
Epoch: 900, accuracy0.848, loss0.493, learning rate 0.048 
Epoch: 1000, accuracy0.855, loss0.483, learning rate 0.047 
Epoch: 1100, accuracy0.848, loss0.512, learning rate 0.047 
Epoch: 1200, accuracy0.862, loss0.462, learning rate 0.047 
Epoch: 1300, accuracy0.857, loss0.466, learning rate 0.047 
Epoch: 1400, accuracy0.856, loss0.474, learning rate 0.047 
Epoch: 1500, accuracy0.855, loss0.446, learning rate 0.046 
Epoch: 1600, accuracy0.858, loss0.456, learning rate

In [43]:
X_test, y_test = spiral_data(samples=100, classes=3)
y_test = one_hot_encode_index(y_test, 3)
model.mode_eval()
model.validate(X_test, y_test)

Validation : Loss: 0.391, Accuracy: 0.850
